### ISSUE TITLE
node example server fails to start

### ISSUE THREAD

**Issue by bigdoods** [fluxio/flux-sdk-js#57]
Hello,

I am just trying to get introduced to the node sdk and I am having some trouble. 

In Flux SDK Node Example repo when I run npm start I receive an error saying that flux-sdk-node module cannot be found. When I look in node_modules, it is there. Can you help please?

**Comment by ftripier** [comment]
Heya! What version of npm/node do you have? We satisfy the "flux-sdk-node" dependency with a feature that was only introduced in npm v2.

**Comment by bigdoods** [comment]
I currently have npm v4.0.3 and node v7.2.0 installed.

**Comment by ftripier** [comment]
Hmm, I can't reproduce so far... What version of the SDK are you using?

**Comment by bigdoods** [comment]
Latest version I think. 4.7

**Comment by bigdoods** [comment]
Here is the Debug.log file.

```0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@4.0.3
3 info using node@v7.2.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle flux-sdk-node-example@0.4.4~prestart: flux-sdk-node-example@0.4.4
6 silly lifecycle flux-sdk-node-example@0.4.4~prestart: no script for prestart, continuing
7 info lifecycle flux-sdk-node-example@0.4.4~start: flux-sdk-node-example@0.4.4
8 verbose lifecycle flux-sdk-node-example@0.4.4~start: unsafe-perm in lifecycle true
9 verbose lifecycle flux-sdk-node-example@0.4.4~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/bigdoods/yano/flux-sdk-js/flux-sdk-node/example/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
10 verbose lifecycle flux-sdk-node-example@0.4.4~start: CWD: /home/bigdoods/yano/flux-sdk-js/flux-sdk-node/example
11 silly lifecycle flux-sdk-node-example@0.4.4~start: Args: [ '-c', 'node ./bin/www' ]
12 silly lifecycle flux-sdk-node-example@0.4.4~start: Returned: code: 1  signal: null
13 info lifecycle flux-sdk-node-example@0.4.4~start: Failed to exec start script
14 verbose stack Error: flux-sdk-node-example@0.4.4 start: `node ./bin/www`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:885:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid flux-sdk-node-example@0.4.4
16 verbose cwd /home/bigdoods/yano/flux-sdk-js/flux-sdk-node/example
17 error Linux 4.4.0-51-generic
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
19 error node v7.2.0
20 error npm  v4.0.3
21 error code ELIFECYCLE
22 error flux-sdk-node-example@0.4.4 start: `node ./bin/www`
22 error Exit status 1
23 error Failed at the flux-sdk-node-example@0.4.4 start script 'node ./bin/www'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the flux-sdk-node-example package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node ./bin/www
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs flux-sdk-node-example
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls flux-sdk-node-example
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by ftripier** [comment]
I'm still having trouble reproducing: can you delete node_modules and rerun npm install?

**Comment by bigdoods** [comment]
Ok - I have solved it. It turns out that I did not have correct permissions set for npm. 

FYI - Something else came up when I deleted everything to start from scratch. When I ran npm install from flux-sdk-node/example I got another error : sh: 1: rimraf: not found. I returned to the flux-sdk-node directory and ran npm install and then tried again and it was fine.

Thanks for your time Felix :+1:

**Comment by ftripier** [comment]
Whew! Yeah, we might install rimraf as a dev dependency in the example directory to fix that. Good luck!
